name: Build and Release

on:
  release:
    types:
      - published
  push:
    branches:
      - 'main'
      - 'beta'
      - 'alpha'

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

env:
  DOTNET_VERSION: '9.0.x'
  
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal --configuration Release


  semantic-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: needs.build-and-test.result == 'success' && github.event_name == 'push'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install npm dependencies
      run: npm install
    
    - name: Run semantic-release
      env:
        GH_TOKEN: ${{ secrets.PAT }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GIT_AUTHOR_NAME: semantic-release-bot
        GIT_AUTHOR_EMAIL: semantic-release-bot@users.noreply.github.com
        GIT_COMMITTER_NAME: semantic-release-bot
        GIT_COMMITTER_EMAIL: semantic-release-bot@users.noreply.github.com
      run: npx semantic-release